version: "3.8"

services:
  whisper:
    container_name: whisper
    build:
      context: .
      dockerfile: Dockerfile
    image: paidax/deploy:asr_fasterwhisper_1.2
    runtime: nvidia
    restart: always
    ports:
      - 7650:7650
    command: uvicorn main:app --port 7650 --host 0.0.0.0
