version: '3.8'
services:
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: paidax/huggingface:1.5
    container_name: huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - $PWD:/home
    command: tail -f /dev/null
    