version: '3.8'
services:
  sadtalker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: paidax/sadtalker:2.2.0
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./main.py:/home/SadTalker/main.py
      - ./src/demo_onnx.py:/home/SadTalker/src/demo_onnx.py
      - ./src/GFPGANReconsitution.py:/home/SadTalker/src/GFPGANReconsitution.py
      - ./src/noise_main.py:/home/SadTalker/src/noise_main.py
      - ./src/utils/face_enhancer_deploy.py:/home/SadTalker/src/utils/face_enhancer_deploy.py
      - ./src/facerender/animate_onnx.py:/home/SadTalker/src/facerender/animate_onnx.py
      - ./src/torch_onnx.py:/home/SadTalker/src/torch_onnx.py
      - ./sadtalker_default.jpeg:/home/SadTalker/sadtalker_default.jpeg
    ports:
      - 10364:10364
    environment:
      - TTS_SERVER=http://192.168.100.20:9566/tts
    command: tail -f /dev/null