version: "3.8"

services:
  whisper:
    container_name: whisper
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: paidax/deploy:asr_fasterwhisper_banchmark_aishell
    runtime: nvidia
    restart: always
    ports:
      - 7650:7650
    command: uvicorn main:app --port 7650 --host 0.0.0.0
