version: '3.8'
services:
  sadtalker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: paidax/sadtalker:light_weight_0.1
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./main.py:/home/SadTalker/main.py
      - ./sadtalker_default.jpeg:/home/SadTalker/sadtalker_default.jpeg
    ports:
      - 10364:10364
    command: uvicorn main:app --host 0.0.0.0 --port 10364