version: '3.8'
services:
  dev-container:
    image: paidax/dev-containers:cuda12.1-py3.11
    ports:
      - 9527:9527
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]