version: '3.8'
services:
  dev-container:
    image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
    ports:
      - 9527:9527
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]