version: '3.8'
services:
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: paidax/openai:0.1
    container_name: openai_api
    command: tail -f /dev/null