version: '3.8'
services:
  funasr_tmp:
    build:
      context: .
      dockerfile: Dockerfile
    image: paidax/funasr:onnx_0.1.0
    container_name: funasr_tmp
    ports:
      - 10095:10095
    command: bash run_server.sh --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-onnx